### ISSUE TITLE
Adding manual centerlines

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#204] opened 2023-01-18 21:44 UTC
hi! 

EDIT: The branch with the latest (corrected) centerlines is `ks/troubleshoot`. New branch was created due to a mix up. Future updates will only be this branch!

**Comment by jcohenadad** [comment] 2023-01-18 21:51
problem identified in sub-04/ses-01: centerline is incomplete:

![image](https://user-images.githubusercontent.com/2482071/213303028-abe9bbc7-ba67-4876-aa74-f59941a9e17d.png)

**Comment by kiristern** [comment] 2023-01-19 03:06
went through the subjects and fixed the centerlines. if @naga-karthik you want to quickly check a few random sub to confirm it's okay? thanks!

**Comment by naga-karthik** [comment] 2023-01-19 21:04
I checked a few more subjects and lgtm! So, the latest branch (with the fixed centrelines) is `ks/centerlines`.

**Comment by naga-karthik** [comment] 2023-01-19 21:14
@jcohenadad could you please merge the latest updates from the branch that's mentioned in [this comment](https://github.com/neuropoly/data-management/issues/204#issuecomment-1397609463)?

**Comment by jcohenadad** [comment] 2023-01-19 21:16
@naga-karthik @kiristern thanks for looking into this! can you please work on a single branch and update the issue so there is no confusion as to what branch to use (two branches are listed in this issue)-- thanks!

**Comment by jcohenadad** [comment] 2023-01-19 21:24
currently reviewing `ks/centerlines`. Any reasons you included the CSV files?
```
.../anat/sub-zh04_ses-01_acq-sag_T2w_centerline-manual.csv      |  717 +++++++------
 .../anat/sub-zh04_ses-01_acq-sag_T2w_centerline-manual.nii.gz   |    2 +-
 .../anat/sub-zh05_ses-01_acq-sag_T2w_centerline-manual.nii.gz   |    2 +-
 .../sub-zh05/sub-zh05_ses-01_acq-sag_T2w_centerline-manual.csv  |  308 ++++++
 .../anat/sub-zh06_ses-01_acq-sag_T2w_centerline-manual.csv      |  975 ++++++++---------
 .../anat/sub-zh06_ses-01_acq-sag_T2w_centerline-manual.nii.gz   |    2 +-
 .../anat/sub-zh06_ses-02_acq-sag_T2w_centerline-manual.csv      | 1022 +++++++++---------
 .../anat/sub-zh06_ses-02_acq-sag_T2w_centerline-manual.nii.gz   |    2 +-
 .../anat/sub-zh09_ses-01_acq-sag_T2w_centerline-manual.csv      |  818 +++++++-------
 .../anat/sub-zh09_ses-01_acq-sag_T2w_centerline-manual.nii.gz   |    2 +-
 .../anat/sub-zh11_ses-01_acq-sag_T2w_centerline-manual.csv      | 1004 +++++++++---------
 .../anat/sub-zh11_ses-01_acq-sag_T2w_centerline-manual.nii.gz   |    2 +-
 .../anat/sub-zh11_ses-02_acq-sag_T2w_centerline-manual.csv      | 1004 +++++++++---------
 .../anat/sub-zh11_ses-02_acq-sag_T2w_centerline-manual.nii.gz   |    2 +-
 .../anat/sub-zh14_ses-01_acq-sag_T2w_centerline-manual.csv      |  858 +++++++--------
 .../anat/sub-zh14_ses-01_acq-sag_T2w_centerline-manual.nii.gz   |    2 +-
 .../anat/sub-zh16_ses-01_acq-sag_T2w_centerline-manual.csv      | 1021 +++++++++---------
 .../anat/sub-zh16_ses-01_acq-sag_T2w_centerline-manual.nii.gz   |    2 +-
 .../anat/sub-zh22_ses-01_acq-sag_T2w_centerline-manual.csv      |  858 +++++++--------
 .../anat/sub-zh22_ses-01_acq-sag_T2w_centerline-manual.nii.gz   |    2 +-
 .../anat/sub-zh36_ses-01_acq-sag_T2w_centerline-manual.csv      |  784 +++++++-------
 .../anat/sub-zh36_ses-01_acq-sag_T2w_centerline-manual.nii.gz   |    2 +-
 .../anat/sub-zh37_ses-01_acq-sag_T2w_centerline-manual.csv      |  962 ++++++++---------
```

**Comment by jcohenadad** [comment] 2023-01-19 21:30
My review:
- sub-zh04/ses-01 ✅ 
- sub-zh05/ses-01 ✅
- sub-zh06/ses-01 ❌

  <details><summary>details</summary>

  You can go a bit higher (C1 is only partially covered by the centerline)
 
  ![image](https://user-images.githubusercontent.com/2482071/213567184-9285b45f-77aa-4a83-8881-35f544f02d26.png)

  </details>

- sub-zh09/ses-01 ✅

**Comment by jcohenadad** [comment] 2023-01-19 21:31
mistake on file location: sci-zurich/derivatives/labels/sub-zh05/sub-zh05_ses-01_acq-sag_T2w_centerline-manual.csv

**Comment by kiristern** [comment] 2023-01-19 23:37
i rm all csv files, as they should not have been incl. and fixed `sub-zh06/ses-01`

**Comment by jcohenadad** [comment] 2023-01-20 03:18
@kiristern I reviewed 9eab8de77d132a886c3e0b091a4e100e990751f8: 

- wrong file location: `sub-zh16/ses-01/anat/sub-zh16_ses-01_acq-sag_T2w_centerline.nii.gz`
- `sub-zh22/ses-01` ✅ 
- `sub-zh49_ses-01` ✅

**Comment by jcohenadad** [comment] 2023-01-20 03:26
@kiristern @naga-karthik can you please delete the branch `nk/add_manual_centerline` (no need to waste physical space and accumulate unnecessary history) and remove its mention here: https://github.com/neuropoly/data-management/issues/204#issue-1548156214 (instead of the EDIT)

**Comment by kiristern** [comment] 2023-01-20 14:47
> wrong file location: sub-zh16/ses-01/anat/sub-zh16_ses-01_acq-sag_T2w_centerline.nii.gz

My mistake, thanks for catching! i moved it to the appropriate derivative folder and also reverted the .csv files because @naga-karthik suggested they could be used for training a regression model

**Comment by kiristern** [comment] 2023-01-20 17:17
@jcohenadad we were having some issues pulling the changes so I created a new branch `ks/troubleshoot` which has all the good files and changes, if you could use that instead to merge to master.

I'm not going to delete the `ks/centerlines` branch just yet, since we want to understand why @naga-karthik isn't able to retrieve the files on `ks/centerlines` nor `ks/troubleshoot` (when he `git pull && git annex sync --no-content && git annex get .` it deleted them -- see the log on `ks/centerlines`). Jan was able to retrieve the files on `ks/troubleshoot`

**Comment by jcohenadad** [comment] 2023-01-20 17:55
hum... maybe @mguaypaq or @kousu can help with these git-annex issues. But on my end I could see the changes, and they can be merged on master whenever you like (so others should also be able to see them once they pull master).

**Comment by naga-karthik** [comment] 2023-01-20 18:45
Sure, if it works on your end, please merge it to master @jcohenadad ! I'll do the surgery on the branch by discussing with @mguaypaq next week. Seems like the problem is specific to me.

**Comment by naga-karthik** [comment] 2023-01-20 18:47
Just to make sure, the latest branch is `ks/troubleshoot` (also updated in the first comment on the issue)

**Comment by mguaypaq** [comment] 2023-01-23 17:32
Just an update: I think we've isolated the problem, which is that `git annex` behaves weirdly on `duke`. Now @naga-karthik has a clean working copy of the repository _outside_ `duke`, so hopefully things will work better.

**Comment by naga-karthik** [comment] 2023-01-23 17:49
@jcohenadad if not already done, can you please merge the branch `ks/troubleshoot` to master so that the additional branches can be deleted? Thank you!

**Comment by jcohenadad** [comment] 2023-01-23 18:12
not done-- will do-- on my todo list-- other priorities

**Comment by jcohenadad** [comment] 2023-01-24 02:45
@naga-karthik there is no branch `ks/troubleshoot`:
````
julien-macbook:~/data.neuro/sci-zurich $ git fetch
julien-macbook:~/data.neuro/sci-zurich $ git branch
  git-annex
  ks/centerlines
* master
  synced/ks/centerlines
  synced/master
````

Are you sure you pushed it to origin?

**Comment by jcohenadad** [comment] 2023-01-24 02:50
`ks/troubleshoot` is not up-to-date with master:

fccc609aeb3336e8d6978306cb0b24db7d825eb3 (HEAD -> master, origin/master, origin/HEAD) modified segmentation

**Comment by jcohenadad** [comment] 2023-01-24 02:52
Bringing it up-to-date:

<details><summary>Terminal output</summary>

```console
julien-macbook:~/data.neuro/sci-zurich $ git merge master          
Merge made by the 'recursive' strategy.
 derivatives/labels/sub-zh56/ses-01/anat/sub-zh56_ses-01_acq-sag_T2w_lesion-manual.json   | 2 +-
 derivatives/labels/sub-zh56/ses-01/anat/sub-zh56_ses-01_acq-sag_T2w_lesion-manual.nii.gz | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)
julien-macbook:~/data.neuro/sci-zurich $ git pull && git annex sync --no-content
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
commit 
On branch ks/troubleshoot
Your branch is ahead of 'origin/ks/troubleshoot' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
ok
pull origin 
ok
push origin 
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 405 bytes | 405.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
To data.neuro.polymtl.ca:datasets/sci-zurich
 * [new branch]      ks/troubleshoot -> synced/ks/troubleshoot
ok

```

</details>

Looking good:

<details><summary>Terminal output</summary>

```console
julien-macbook:~/data.neuro/sci-zurich $ git diff --name-only master..HEAD
derivatives/labels/sub-zh04/ses-01/anat/sub-zh04_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh04/ses-01/anat/sub-zh04_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh05/ses-01/anat/sub-zh05_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh05/ses-01/anat/sub-zh05_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh06/ses-01/anat/sub-zh06_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh06/ses-01/anat/sub-zh06_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh06/ses-02/anat/sub-zh06_ses-02_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh06/ses-02/anat/sub-zh06_ses-02_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh09/ses-01/anat/sub-zh09_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh09/ses-01/anat/sub-zh09_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh11/ses-01/anat/sub-zh11_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh11/ses-01/anat/sub-zh11_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh11/ses-02/anat/sub-zh11_ses-02_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh11/ses-02/anat/sub-zh11_ses-02_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh14/ses-01/anat/sub-zh14_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh14/ses-01/anat/sub-zh14_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh16/ses-01/anat/sub-zh16_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh16/ses-01/anat/sub-zh16_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh22/ses-01/anat/sub-zh22_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh22/ses-01/anat/sub-zh22_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh36/ses-01/anat/sub-zh36_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh36/ses-01/anat/sub-zh36_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh37/ses-01/anat/sub-zh37_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh37/ses-01/anat/sub-zh37_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh48/ses-01/anat/sub-zh48_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh48/ses-01/anat/sub-zh48_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh49/ses-01/anat/sub-zh49_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh49/ses-01/anat/sub-zh49_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh68/ses-01/anat/sub-zh68_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh68/ses-01/anat/sub-zh68_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh69/ses-01/anat/sub-zh69_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh69/ses-01/anat/sub-zh69_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh77/ses-01/anat/sub-zh77_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh77/ses-01/anat/sub-zh77_ses-01_acq-sag_T2w_centerline-manual.nii.gz
derivatives/labels/sub-zh78/ses-01/anat/sub-zh78_ses-01_acq-sag_T2w_centerline-manual.csv
derivatives/labels/sub-zh78/ses-01/anat/sub-zh78_ses-01_acq-sag_T2w_centerline-manual.nii.gz

```

</details>

**Comment by jcohenadad** [comment] 2023-01-24 02:57
Convenient script for QCing (replace 04 05 by start end):

```
for i in $(seq -f "%02g" 04 05); do fsleyes -S sub-zh${i}/ses-01/anat/sub-zh${i}_ses-01_acq-sag_T2w  derivatives/labels/sub-zh${i}/ses-01/anat/sub-zh${i}_ses-01_acq-sag_T2w_centerline-manual -cm red; done
```

**Comment by jcohenadad** [comment] 2023-01-24 03:01
merged and cleaned up:

<details><summary>Terminal output</summary>

```console
julien-macbook:~/data.neuro/sci-zurich $ git merge ks/troubleshoot
Updating fccc609..9486a83
Fast-forward
 derivatives/labels/sub-zh04/ses-01/anat/sub-zh04_ses-01_acq-sag_T2w_centerline-manual.csv    | 422 ++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh04/ses-01/anat/sub-zh04_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh05/ses-01/anat/sub-zh05_ses-01_acq-sag_T2w_centerline-manual.csv    | 308 ++++++++++++++++++++++++++++
 derivatives/labels/sub-zh05/ses-01/anat/sub-zh05_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh06/ses-01/anat/sub-zh06_ses-01_acq-sag_T2w_centerline-manual.csv    | 464 +++++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh06/ses-01/anat/sub-zh06_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh06/ses-02/anat/sub-zh06_ses-02_acq-sag_T2w_centerline-manual.csv    | 511 +++++++++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh06/ses-02/anat/sub-zh06_ses-02_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh09/ses-01/anat/sub-zh09_ses-01_acq-sag_T2w_centerline-manual.csv    | 409 +++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh09/ses-01/anat/sub-zh09_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh11/ses-01/anat/sub-zh11_ses-01_acq-sag_T2w_centerline-manual.csv    | 511 +++++++++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh11/ses-01/anat/sub-zh11_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh11/ses-02/anat/sub-zh11_ses-02_acq-sag_T2w_centerline-manual.csv    | 511 +++++++++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh11/ses-02/anat/sub-zh11_ses-02_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh14/ses-01/anat/sub-zh14_ses-01_acq-sag_T2w_centerline-manual.csv    | 447 ++++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh14/ses-01/anat/sub-zh14_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh16/ses-01/anat/sub-zh16_ses-01_acq-sag_T2w_centerline-manual.csv    | 510 +++++++++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh16/ses-01/anat/sub-zh16_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh22/ses-01/anat/sub-zh22_ses-01_acq-sag_T2w_centerline-manual.csv    | 447 ++++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh22/ses-01/anat/sub-zh22_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh36/ses-01/anat/sub-zh36_ses-01_acq-sag_T2w_centerline-manual.csv    | 375 ++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh36/ses-01/anat/sub-zh36_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh37/ses-01/anat/sub-zh37_ses-01_acq-sag_T2w_centerline-manual.csv    | 481 +++++++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh37/ses-01/anat/sub-zh37_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh48/ses-01/anat/sub-zh48_ses-01_acq-sag_T2w_centerline-manual.csv    | 761 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh48/ses-01/anat/sub-zh48_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh49/ses-01/anat/sub-zh49_ses-01_acq-sag_T2w_centerline-manual.csv    | 372 +++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh49/ses-01/anat/sub-zh49_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh68/ses-01/anat/sub-zh68_ses-01_acq-sag_T2w_centerline-manual.csv    | 366 +++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh68/ses-01/anat/sub-zh68_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh69/ses-01/anat/sub-zh69_ses-01_acq-sag_T2w_centerline-manual.csv    | 447 ++++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh69/ses-01/anat/sub-zh69_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh77/ses-01/anat/sub-zh77_ses-01_acq-sag_T2w_centerline-manual.csv    | 340 ++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh77/ses-01/anat/sub-zh77_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 derivatives/labels/sub-zh78/ses-01/anat/sub-zh78_ses-01_acq-sag_T2w_centerline-manual.csv    | 442 +++++++++++++++++++++++++++++++++++++++
 derivatives/labels/sub-zh78/ses-01/anat/sub-zh78_ses-01_acq-sag_T2w_centerline-manual.nii.gz |   1 +
 36 files changed, 8142 insertions(+)
 create mode 100644 derivatives/labels/sub-zh04/ses-01/anat/sub-zh04_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh04/ses-01/anat/sub-zh04_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh05/ses-01/anat/sub-zh05_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh05/ses-01/anat/sub-zh05_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh06/ses-01/anat/sub-zh06_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh06/ses-01/anat/sub-zh06_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh06/ses-02/anat/sub-zh06_ses-02_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh06/ses-02/anat/sub-zh06_ses-02_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh09/ses-01/anat/sub-zh09_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh09/ses-01/anat/sub-zh09_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh11/ses-01/anat/sub-zh11_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh11/ses-01/anat/sub-zh11_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh11/ses-02/anat/sub-zh11_ses-02_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh11/ses-02/anat/sub-zh11_ses-02_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh14/ses-01/anat/sub-zh14_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh14/ses-01/anat/sub-zh14_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh16/ses-01/anat/sub-zh16_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh16/ses-01/anat/sub-zh16_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh22/ses-01/anat/sub-zh22_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh22/ses-01/anat/sub-zh22_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh36/ses-01/anat/sub-zh36_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh36/ses-01/anat/sub-zh36_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh37/ses-01/anat/sub-zh37_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh37/ses-01/anat/sub-zh37_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh48/ses-01/anat/sub-zh48_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh48/ses-01/anat/sub-zh48_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh49/ses-01/anat/sub-zh49_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh49/ses-01/anat/sub-zh49_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh68/ses-01/anat/sub-zh68_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh68/ses-01/anat/sub-zh68_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh69/ses-01/anat/sub-zh69_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh69/ses-01/anat/sub-zh69_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh77/ses-01/anat/sub-zh77_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh77/ses-01/anat/sub-zh77_ses-01_acq-sag_T2w_centerline-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh78/ses-01/anat/sub-zh78_ses-01_acq-sag_T2w_centerline-manual.csv
 create mode 100644 derivatives/labels/sub-zh78/ses-01/anat/sub-zh78_ses-01_acq-sag_T2w_centerline-manual.nii.gz
julien-macbook:~/data.neuro/sci-zurich $ git push
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To data.neuro.polymtl.ca:datasets/sci-zurich
   fccc609..9486a83  master -> master
julien-macbook:~/data.neuro/sci-zurich $ git branch -d ks/troubleshoot
Deleted branch ks/troubleshoot (was 9486a83).
julien-macbook:~/data.neuro/sci-zurich $ git push origin :ks/troubleshoot                  
To data.neuro.polymtl.ca:datasets/sci-zurich
 - [deleted]         ks/troubleshoot

```

</details>

**Comment by jcohenadad** [comment] 2023-01-24 03:03
Additional cleanup

<details><summary>Terminal output</summary>

```console
julien-macbook:~/data.neuro/sci-zurich $ gb
  git-annex
  ks/centerlines
* master
  synced/ks/centerlines
  synced/ks/troubleshoot
  synced/master
julien-macbook:~/data.neuro/sci-zurich $ git branch -d ks/centerlines
warning: deleting branch 'ks/centerlines' that has been merged to
         'refs/remotes/origin/ks/centerlines', but not yet merged to HEAD.
Deleted branch ks/centerlines (was 8d79a4b).
julien-macbook:~/data.neuro/sci-zurich $ git push origin :ks/centerlines
To data.neuro.polymtl.ca:datasets/sci-zurich
 - [deleted]         ks/centerlines
julien-macbook:~/data.neuro/sci-zurich $ git branch -d synced/ks/centerlines
Deleted branch synced/ks/centerlines (was fbfdde7).
julien-macbook:~/data.neuro/sci-zurich $ git push origin :synced/ks/centerlines
To data.neuro.polymtl.ca:datasets/sci-zurich
 - [deleted]         synced/ks/centerlines
julien-macbook:~/data.neuro/sci-zurich $ git branch -d synced/ks/troubleshoot
Deleted branch synced/ks/troubleshoot (was 9486a83).
julien-macbook:~/data.neuro/sci-zurich $ git push origin :synced/ks/troubleshoot
To data.neuro.polymtl.ca:datasets/sci-zurich
 - [deleted]         synced/ks/troubleshoot
julien-macbook:~/data.neuro/sci-zurich $ gb
  git-annex
* master
  synced/master

```

</details>

**Comment by naga-karthik** [comment] 2023-03-30 11:48
After running `sct_get_centerline` on the latest cohort of 16 more subjects, I found an error with `sub-zh87`. I had to manually create the centerline using the steps mentioned [here](https://github.com/ivadomed/model_seg_sci/tree/main/preprocessing#performing-manual-qc-for-centerline-extraction). This can be found under my branch `nk/manual_centerline_new_cohort`. Here's how the manual correction looks: 

<img width="245" alt="Screen Shot 2023-03-30 at 5 16 44 PM" src="https://user-images.githubusercontent.com/53445351/228826268-88a0a838-dc3a-438c-9321-f6ab867bc997.png">

@mguaypaq can you please merge it to master? Thanks in advance!

**Comment by jcohenadad** [comment] 2023-03-30 13:11
it would be really nice to have a proper QC for centerline, ie: where we can see it from top to bottom without interruption. Tagging @joshuacwnewton so he is aware of this feature request (i _think_ we already have an issue open about this)

**Comment by naga-karthik** [comment] 2023-03-30 15:01
Agreed! 

Thanks to @valosekj's suggestion, I use `sct_label_vertebrae` while running `sct_qc` as a workaround to visualize the centerline on the sagittal plane (check [this](https://github.com/ivadomed/model_seg_sci/blob/main/preprocessing/preprocess_zurich_centerline.sh#L72-L73) to see how it is run). The result is quite decent and it looks something like the one shown below: 

<details> 

<summary> Workaround QC </summary>

<img width="505" alt="Screen Shot 2023-03-30 at 8 29 57 PM" src="https://user-images.githubusercontent.com/53445351/228878771-3af6554e-7896-4701-b71f-414950c12e9c.png">

</details>

**Comment by joshuacwnewton** [comment] 2023-03-30 16:17
> Tagging @joshuacwnewton so he is aware of this feature request (i _think_ we already have an issue open about this)

* https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4011

In that issue, @valosekj describes the [exact same workaround](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4011#issuecomment-1403828459) that @naga-karthik has mentioned above.

**Comment by mguaypaq** [comment] 2023-04-03 19:17
> This can be found under my branch `nk/manual_centerline_new_cohort`. [...]
> @mguaypaq can you please merge it to master? Thanks in advance!

Done! `git annex get` is happy, so I merged into master.

**Comment by valosekj** [comment] 2023-06-23 14:11
Closing since the branch was merged into master. 
Moreover, we have now also SC segmentations, see https://github.com/neuropoly/data-management/issues/238

**Closed as completed by valosekj** 2023-06-23 14:11 UTC
Labels: dataset: sci-zurich
