### ISSUE TITLE
New dataset marseille-3T-mp2rage

### ISSUE THREAD

**Issue by Nilser3** [neuropoly/data-management#260] opened 2023-09-07 21:24 UTC
# Description 
Hi @mguaypaq 

This is a new dataset of MS patients from Marseille, acquired at 3T with a MP2RAGE sequence, contains UNIT1 contrast and manual segmentation of MS lesions.

This dataset regroups large fields-of-view (FOV) containing head and spinal cord from C1 to C7 (MS lesions were segmented only in the spinal cord) of 27 subjects, of which 14 have M24 follow-up.

Working branch: `nm/initial_data`

### BIDSification :

<details><summary>bids-validator</summary>

```console

# bids-validator marseille-3T-mp2rage --verbose

bids-validator@1.11.0

(node:27848) Warning: Closing directory handle on garbage collection

(Use `node --trace-warnings ...` to show where the warning was created)

        1: [WARN] Tabular file contains custom columns not described in a data dictionary (code: 82 - CUSTOM_COLUMN_WITHOUT_DESCRIPTION)
                ./participants.tsv
                        Tabular file contains custom columns not described in a data dictionary
                        Evidence: Columns: sex, age not defined, please define in: /participants.json

        Please visit https://neurostars.org/search?q=CUSTOM_COLUMN_WITHOUT_DESCRIPTION for existing conversations about this issue.

        2: [WARN] Not all subjects contain the same sessions. (code: 97 - MISSING_SESSION)
                ./sub-MRS00/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS00; Missing session: ses-M24
                ./sub-MRS04/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS04; Missing session: ses-M24
                ./sub-MRS05/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS05; Missing session: ses-M24
                ./sub-MRS07/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS07; Missing session: ses-M24
                ./sub-MRS10/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS10; Missing session: ses-M24
                ./sub-MRS13/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS13; Missing session: ses-M24
                ./sub-MRS16/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS16; Missing session: ses-M24
                ./sub-MRS17/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS17; Missing session: ses-M24
                ./sub-MRS18/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS18; Missing session: ses-M24
                ./sub-MRS20/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS20; Missing session: ses-M24
                ./sub-MRS22/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS22; Missing session: ses-M24
                ./sub-MRS25/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS25; Missing session: ses-M24
                ./sub-MRS26/ses-M24
                        A session is missing from one subject that is present in at least one other subject
                        Evidence: Subject: sub-MRS26; Missing session: ses-M24

        Please visit https://neurostars.org/search?q=MISSING_SESSION for existing conversations about this issue.

        3: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)

        Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.

        Summary:                  Available Tasks:        Available Modalities:
        43 Files, 957.17MB                                MRI
        27 - Subjects
        2 - Sessions


        If you have any questions, please post on https://neurostars.org/tags/bids.
```
</details>

The dataset is currently available at: `rosenberg/data_nvme_nilaia/marseille-3T-mp2rage`

## Related issues:

[MS MP2RAGE lesion segmentation](https://github.com/ivadomed/model_seg_ms_mp2rage/issues/75)

**Comment by jcohenadad** [comment] 2023-09-08 13:07
Mention in the README that the data are property of Virginie Callot's group, and should not be used for other projects unless specific authorization

**Comment by mguaypaq** [comment] 2023-09-14 20:49
Hi @Nilser3, sorry for the delay. Thanks for preparing this dataset, and for running bids-validator on it. The warnings look like they will be easy to fix.

I created the repository on data.neuro.polymtl.ca, and gave you write access, so you'll be able to:
1. clone the repository (`git clone git@data.neuro.polymtl.ca:datasets/marseille-3T-mp2rage`);
2. create a branch (something like `git checkout -b nm/initial_data`); and
3. upload your data, following the instructions at [this link](https://intranet.neuro.polymtl.ca/data/git-datasets.html#upload).

(I don't have access `rosenberg/data_nvme_nilaia/marseille-3T-mp2rage`, which is normal, but it means that I can't do the initial upload myself.)

Let me know if you run into any issues. Once you've uploaded the data, we can fix the bids-validator warnings, and merge your branch into master.

**Comment by jcohenadad** [comment] 2023-09-15 14:05
The JSON of the SC segmentation should also include the native segmentation done with SCT (and its tool and version).

Moreover, the tag "Label" is probably useless. @valosekj can confirm

**Comment by Nilser3** [comment] 2023-09-15 18:31
Hi @mguaypaq 

Thanks for the clarification,

I have followed the steps and I have:

```
(base) nilaia@rosenberg:~/data_nvme_nilaia/marseille-3T-mp2rage$ git push
Énumération des objets: 393, fait.
Décompte des objets: 100% (393/393), fait.
Compression par delta en utilisant jusqu'à 40 fils d'exécution
Compression des objets: 100% (284/284), fait.
Écriture des objets: 100% (392/392), 957.66 Mio | 16.09 Mio/s, fait.
Total 392 (delta 153), réutilisés 0 (delta 0), réutilisés du pack 0
remote: Résolution des deltas: 100% (153/153), fait.
To data.neuro.polymtl.ca:datasets/marseille-3T-mp2rage
 * [new branch]      nm/initial_data -> nm/initial_data
```

So, I think it's ready for a PR?

**Comment by valosekj** [comment] 2023-09-15 19:34
Thank you @Nilser3!

---

> The JSON of the SC segmentation should also include the native segmentation done with SCT (and its tool and version).

Good point! See [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3394#issue-894485189), @Nilser3.

Example:

```json
{
  "GeneratedBy": [
    {
      "Name": "sct",
      "Version": "5.3.0",
    },
    {
      "Author": "John Doe",
      "Description": "Manual correction of spinal cord segmentation",
      "Date": "2021-05-10 10:10:28",
    }
  ]
}
```

---

> Moreover, the tag "Label" is probably useless. @valosekj can confirm

Confirm. The `Label` key-value pair can be deleted from the JSON sidecars.

```console
$ cat derivatives/labels/sub-MRS00/ses-M0/anat/sub-MRS00_ses-M0_UNIT1_label-SC_seg.json
{
  "Author": "Samirah Mchinda",
  "Label": "label-SC_seg",
  "Date": "2019-01-01"
}%
```
---

For the lesion labels:

```console
$ ls derivatives/labels/sub-MRS00/ses-M0/anat/*lesion*nii.gz
sub-MRS00_ses-M0_UNIT1_manual_labels_lesionConsensusNilser.nii.gz
sub-MRS00_ses-M0_UNIT1_manual_labels_lesionSarah.nii.gz
```

Instead of `manual_labels_lesion` suffix, we use `label-lesion` (see [intranet](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#derivatives-structure)).

Also, instead of names (`Sarah` and `Nilser`), we usually use `_rater1`, `_rater2`, etc. Names are included in the JSON sidecars.

---

BTW the `git clone git@data.neuro.polymtl.ca:datasets/marseille-3T-mp2rage` command took a looong time on my side! Maybe you might have pushed the nii files directly to git instead of `git-annex`, @Nilser3. @mguaypaq correct me if I am wrong.

**Comment by mguaypaq** [comment] 2023-09-18 17:03
> BTW the `git clone git@data.neuro.polymtl.ca:datasets/marseille-3T-mp2rage` command took a looong time on my side! Maybe you might have pushed the nii files directly to git instead of `git-annex`, @Nilser3. @mguaypaq correct me if I am wrong.

That's right, the image files are not correctly git-annexed, but I can fix this.

@Nilser3, did you run the following commands, from the instructions I linked?
```bash
# before doing 'git add' and 'git commit':
git annex dead here

# after doing 'git add' and 'git commit':
git annex copy --all --to=origin
git annex sync --no-content --only-annex
git push
```
It looks like you only ran the `git push` command.

**Comment by mguaypaq** [comment] 2023-09-18 17:49
Ok, I fixed the image files to be git-annexed, which involved re-writing the branch `nm/initial_data`. @jcohenadad, @valosekj, @Nilser3, if you have any local clones of the `datasets/marseille-3T-mp2rage` repositories, can you delete them and re-clone? And remember to run `git annex dead here` (only needed once) before adding or modifying any image files.

**Comment by Nilser3** [comment] 2023-09-18 17:53
Hi @mguaypaq , 

I just verified in my _history_ that I had not executed the `git annex dead here' part.
But the other commands were executed

**Comment by mguaypaq** [comment] 2023-09-18 19:03
Ah ok, that would explain it yes. It's easy to miss this command!

**Comment by jcohenadad** [comment] 2023-09-29 14:11
hey team! any progress on that?

**Comment by jcohenadad** [comment] 2023-09-29 14:11
i'd like to review before merging pls-- let me know when is a good time for review

**Comment by jcohenadad** [comment] 2023-09-29 14:20
Looking at bb483c791e37d34d433fe53f2f35ff13d5d8067d

Based on @valosekj:

> Confirm. The Label key-value pair can be deleted from the JSON sidecars.

However, I see that the field was _not_ removed:

~~~
julien-macbook:~/data.neuro/marseille-3T-mp2rage $ cat derivatives/labels/sub-MRS00/ses-M0/anat/sub-MRS00_ses-M0_UNIT1_label-lesion_rater1.json 
{
  "Author": "Sarah Demortière",
  "Label": "label-lesion_rater1",
  "Date": "2019-01-01"
}
~~~

@Nilser3 please proceed as we all agreed on and let us know when the PR is ready for review

**Comment by Nilser3** [comment] 2023-09-29 17:37
Hi @mguaypaq 

I have corrected @jcohenadad  observations,
I'm ready for PR

**Comment by mguaypaq** [comment] 2023-09-29 20:02
Thanks.

I can confirm that the README mentions that the data are property of Virginie Callot's group, and should not be used for other projects unless specific authorization, so that's good.

While trying to confirm that the "Label" tags were all gone, I discovered that the folder structure has a problem: it looks like there's a second copy of the entire dataset inside the subject folder `sub-MRS26`. Should I remove it, and leave only the `sub-MRS26/ses-M0` subfolder?

Other than that, the filenames look right (`label-lesion`, `_rater1`, `_rater2`).

There's a missing file `participants.json` to describe the columns in `participants.tsv`, you can see an example of the correct format [at this link](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#participants-json). This seems to be the only important warning from bids-validator.

**Comment by Nilser3** [comment] 2023-10-02 13:40
Hi @mguaypaq 

Thank you for your comments,
Indeed, I had a problem in the `sub-MRS26`, I solved it
Likewise, I have already added the `participants.json` file

I think I'm ready for a PR

**Comment by mguaypaq** [comment] 2023-10-02 18:52
I fixed some minor remaining issues by adding some commits to the branch `nm/initial_data`. At this point, the files names, formats, and directory structure are OK, git-annex is OK, and bids-validator is OK.

@jcohenadad and/or @valosekj: the branch is now ready for a final review before merging.

**Comment by jcohenadad** [comment] 2023-10-02 21:08
I checked `sub-MRS00` and assuming the other subjects are like that, everything is fine on my end to be merged. Thank you @Nilser3 @mguaypaq 🙏

**Comment by mguaypaq** [comment] 2023-10-02 21:23
Great, I merged into `master`, and deleted the branch `nm/initial_data`.

**Closed as completed by mguaypaq** 2023-10-02 21:23 UTC
