### ISSUE TITLE
Add additional data karo (lesion-manual) sct-testing-large

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/data-management#85] opened 2021-06-04 15:37 UTC
We have received more segmented lesions from Anne for karo data.

We want to find which files are unique in order not to overwrite the files in sct-testing-large.

Tested fdupes: http://showterm.io/aed2544641cd410d50b2c but didn't work well.

Tested diff: http://showterm.io/7b36140732479a6966827 and it works well, but hard to implement in python.

Tried : 

```
from filecmp import dircmp
def print_diff_files(dcmp):
    for name in dcmp.diff_files:
        print("diff_file %s found in %s and %s" % (name, dcmp.left,
              dcmp.right))
    for sub_dcmp in dcmp.subdirs.values():
        print_diff_files(sub_dcmp)

dcmp = dircmp( '/home/alfoi_admin/data/sct-testing-large','/home/alfoi_admin/data/Segmentations_karo_AK_curated') 
print_diff_files(dcmp) 
```
 And got this:
```
(base) alfoi_admin@tristano:~/code/personal_scripts/python/unsorted$ python compare_files.py 
diff_file participants.tsv found in /home/alfoi_admin/data/sct-testing-large and /home/alfoi_admin/data/Segmentations_karo_AK_curated
diff_file sub-karo1781_acq-sagcerv_T2star_lesion-manual.nii.gz found in /home/alfoi_admin/data/sct-testing-large/derivatives/labels/sub-karo1781/anat and /home/alfoi_admin/data/Segmentations_karo_AK_curated/derivatives/labels/sub-karo1781/anat
diff_file sub-karo1822_acq-sagcerv_T2star_lesion-manual.nii.gz found in /home/alfoi_admin/data/sct-testing-large/derivatives/labels/sub-karo1822/anat and /home/alfoi_admin/data/Segmentations_karo_AK_curated/derivatives/labels/sub-karo1822/anat
diff_file sub-karo1846_acq-sagcerv_T2star_lesion-manual.nii.gz found in /home/alfoi_admin/data/sct-testing-large/derivatives/labels/sub-karo1846/anat and /home/alfoi_admin/data/Segmentations_karo_AK_curated/derivatives/labels/sub-karo1846/anat
diff_file sub-karo1898_acq-sagcerv_T2star_lesion-manual.nii.gz found in /home/alfoi_admin/data/sct-testing-large/derivatives/labels/sub-karo1898/anat and /home/alfoi_admin/data/Segmentations_karo_AK_curated/derivatives/labels/sub-karo1898/anat
diff_file sub-karo2011_acq-sagcerv_T2star_lesion-manual.nii.gz found in /home/alfoi_admin/data/sct-testing-large/derivatives/labels/sub-karo2011/anat and /home/alfoi_admin/data/Segmentations_karo_AK_curated/derivatives/labels/sub-karo2011/anat
diff_file sub-karo2039_acq-sagcerv_T2star_lesion-manual.nii.gz found in /home/alfoi_admin/data/sct-testing-large/derivatives/labels/sub-karo2039/anat and /home/alfoi_admin/data/Segmentations_karo_AK_curated/derivatives/labels/sub-karo2039/anat
diff_file sub-karo2046_acq-sagcerv_T2star_lesion-manual.nii.gz found in /home/alfoi_admin/data/sct-testing-large/derivatives/labels/sub-karo2046/anat and /home/alfoi_admin/data/Segmentations_karo_AK_curated/derivatives/labels/sub-karo2046/anat
diff_file sub-karo2050_acq-sagcerv_T2star_lesion-manual.nii.gz found in /home/alfoi_admin/data/sct-testing-large/derivatives/labels/sub-karo2050/anat and /home/alfoi_admin/data/Segmentations_karo_AK_curated/derivatives/labels/sub-karo2050/anat
diff_file sub-karo2123_acq-sagcerv_T2star_lesion-manual.nii.gz found in /home/alfoi_admin/data/sct-testing-large/derivatives/labels/sub-karo2123/anat and /home/alfoi_admin/data/Segmentations_karo_AK_curated/derivatives/labels/sub-karo2123/anat
```

So far `diff` generates the best results. 

Is there any python function that might get the same results ? This will help some time from writing the parser for `diff`.

**Comment by kousu** [comment] 2021-06-04 16:10
The python version can be written shorter as `diff -r` btw. (`diff -r` is great; I use it all the time). But it's only good for comparing two diverged copies of the same directory. `fdupes` is more general, and can handle finding duplicates no matter what they are named or what folder they are in. Is this in the simpler `diff -r` case or not?

I think, if you are in the `diff -r` case, meaning that all your new segmentations have an **identical naming scheme**, then you can skip `diff` or `fdupes` and merge the new files in directly with `cp -r` or `rsync -r`. Then `git` will take care of detected what's changed: `git status` will partition the changes by `new file` and `modified`, and you want the 'modified' set to be empty.

**Comment by kousu** [comment] 2021-06-04 16:58
If you're in the more complicated `fdupes` case, you just need to script a little bit. In that case you're trying to compute the set difference `Segmentations_karo_AK_curated/ \ sct-testing-large/`, based on file hashes. You can do it with this:

```
comm -23 <(find Segmentations_karo_AK_curated/  | sort) <(fdupes -i -f -r Segmentations_karo_AK_curated/  sct-testing-large/ | sort)
```

`-f` suppresses the first match in each matchset and `-i` makes sure that that means `sct-testing-large/` (see [the docs](https://github.com/adrianlopezroche/fdupes#readme) for `-i`). So it reports all the files in `Segmentations_karo_AK_curated/` that are duplicates, then it subtracts them from the total set using [`comm -23`](https://catonmat.net/set-operations-in-unix-shell) from the source, and you're left with only new files

<details><summary>minimal example</summary>

```
# */t0 are different files, under the same name
# */t1 are duplicates, under the same name
# */t2 amd */t3 are duplicates, but under a different name
# */t4 and */t5 are different files, under different names
$ tree
.
├── sct-testing-large
│   ├── t0
│   ├── t1
│   ├── t3
│   └── t5
└── Segmentations_karo_AK_curated
    ├── t0
    ├── t1
    ├── t2
    └── t4

2 directories, 8 files
$ egrep -r "*"
sct-testing-large/t5:nnn
sct-testing-large/t0:aaa
sct-testing-large/t3:kkk
sct-testing-large/t1:zzz
Segmentations_karo_AK_curated/t0:bbb
Segmentations_karo_AK_curated/t4:jjj
Segmentations_karo_AK_curated/t2:kkk
Segmentations_karo_AK_curated/t1:zzz
```

This produced

```
$ comm -23 <(find Segmentations_karo_AK_curated/ | sort) <(fdupes -r -f -i sct-testing-large/ Segmentations_karo_AK_curated/ | sort)
Segmentations_karo_AK_curated/          
Segmentations_karo_AK_curated/t0
Segmentations_karo_AK_curated/t4
```

So it found the new files t0 and t4. It *skipped* t2 which is a duplicate of t3, even though it has a different name.

</details>


I tested this with

```
$ fdupes -v
fdupes 2.1.2
```

Which outputs this simpler groups-of-lines format by default:

```
$ fdupes -r sct-testing-large/ Segmentations_karo_AK_curated/
Segmentations_karo_AK_curated/t1        
sct-testing-large/t1

Segmentations_karo_AK_curated/t2
sct-testing-large/t3
```

It seems that debian, even the [latest debian](https://packages.debian.org/search?keywords=fdupes) still has version 1. But we can backport this script to version 1, just needs more `awk` (you can solve a lot of things with `awk`).

**Comment by kousu** [comment] 2021-06-08 17:20
Hey @alexfoias, we talked on slack about just letting `git` tell you what the duplicate files were. Did that work out for you?

**Comment by kousu** [comment] 2021-06-08 17:21
Also is this related to https://github.com/ivadomed/ivadomed/issues/65 ? It seems like the same problem.

**Comment by kousu** [comment] 2021-11-25 18:28
This data seems to have been successfully added in commit 31ddc826f854c00eb73afbcb1eafbdaf879f4786 months ago:

```
commit 31ddc826f854c00eb73afbcb1eafbdaf879f4786 (synced/master)
Author: Alexandru Foias <afoias@polymtl.ca>
Date:   Tue Jun 8 09:38:26 2021 -0400

    add lesion segmentation karo

diff --git a/derivatives/labels/sub-karo1781/anat/sub-karo1781_acq-tho_T2star_lesion-manual.json b/derivatives/labels/sub-karo1781/anat/sub-karo1781_acq-tho_T2star_lesion-manual.json
new file mode 100644
index 0000000000..0760a1170d
--- /dev/null
+++ b/derivatives/labels/sub-karo1781/anat/sub-karo1781_acq-tho_T2star_lesion-manual.json
@@ -0,0 +1,4 @@
+{
+  "Author": "Anne Kerbrat",
+  "Label": "lesion-manual"
+}
\ No newline at end of file
diff --git a/derivatives/labels/sub-karo1781/anat/sub-karo1781_acq-tho_T2star_lesion-manual.nii.gz b/derivatives/labels/sub-karo1781/anat/sub-karo1781_acq-tho_T2star_lesion-manual.nii.gz
new file mode 100644
index 0000000000..aa07cfaa3b
--- /dev/null
+++ b/derivatives/labels/sub-karo1781/anat/sub-karo1781_acq-tho_T2star_lesion-manual.nii.gz
@@ -0,0 +1 @@
+/annex/objects/SHA256E-s5715--70724c912550ce1372d97412ae374851b36174b7953c971fe6f6bd016fc841ec.nii.gz
```

**Closed by kousu** 2021-11-25 18:28 UTC
Labels: ://data.neuro.polymtl.ca, dataset: sct-testing-large, gitolite pr
