### ISSUE TITLE
Find a better naming to distinguish histology from MRI data

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#110] opened 2021-07-22 15:35 UTC
Currently, the list looks like this:
~~~
 R W	datasets/basel-mp2rage --> MRI
 R W	datasets/data-single-subject_DO-NOT-USE --> MRI
 R W	datasets/data_axondeepseg_tem --> HISTO
 R W	datasets/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg --> MRI
 R W	datasets/msseg_challenge_2016 --> MRI
 R W	datasets/msseg_challenge_2021 --> MRI
 R W	datasets/msseg_challenge_2021_DO-NOT-USE --> MRI
 R W	datasets/sci-zurich --> MRI
 R W	datasets/sct-testing-large --> MRI
 R W	datasets/spine-generic-processed --> MRI
 R W	datasets/uk-biobank --> MRI
 R W	datasets/uk-biobank-processed --> MRI
 R W	datasets/wakehealth --> HISTO
 R W	gitolite-admin --> ?
~~~

It would probably be a good idea to at least find a way to distinguish MRI from HISTO data more conveniently.

**Comment by kousu** [comment] 2021-09-26 23:23
Duplicate of #120

**Closed by kousu** 2021-09-26 23:23 UTC
Labels: enhancement
